language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    allow_failures:
      - php: 'nightly'
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
          env: WITH_COVERAGE=true
        - php: 7.1
        - php: 'nightly'
        - php: hhvm

before_script:
    - if [[ "$WITH_COVERAGE" != "true" ]]; then phpenv config-rm xdebug.ini || true; fi
    - composer selfupdate
    - mkdir -p build/logs

script:
    - travis_retry composer install --no-interaction
    - composer style
    - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml --coverage-text; else vendor/bin/phpunit -c phpunit.xml; fi
    - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/coveralls -v; fi;
